#!/bin/bash

set -euxo pipefail

STEMCELL_OS="${STEMCELL_OS:-ubuntu-xenial}"
STEMCELL_IAAS="${STEMCELL_IAAS:-google-kvm}"

pushd "$(dirname "$0")/.."
  bosh create-release --force --version="$(date "+%s")"
  bosh upload-release
popd

bosh upload-stemcell "https://bosh.io/d/stemcells/bosh-${STEMCELL_IAAS}-${STEMCELL_OS}-go_agent"

pushd "$(dirname "$0")/../tests"
  go install github.com/onsi/ginkgo/v2/ginkgo
  ginkgo -r --procs="${NODES:-3}" --compilers="${NODES:-3}" --keep-going --timeout="4h" "$@"
popd
